-- insert_sample_data.sql
-- Inserts sample data into the University Student Management System database

-- Academic Schema
-- Insert faculties
INSERT INTO academic.faculties (faculty_name) VALUES
    ('FACULTATEA DE BIOLOGIE SI PEDOLOGIE'),
    ('FACULTATEA DE DREPT'),
    ('FACULTATEA DE CHIMIE ŞI TEHNOLOGIE CHIMICĂ'),
    ('FACULTATEA DE FIZICA SI INGINERIE'),
    ('FACULTATEA DE ISTORIE ŞI FILOSOFIE'),
    ('FACULTATEA DE JURNALISM ŞI ŞTIINŢE ALE COMUNICĂRII'),
    ('FACULTATEA DE LITERE'),
    ('FACULTATEA DE MATEMATICĂ ŞI INFORMATICĂ'),
    ('FACULTATEA PSIHOLOGIE, ŞTIINŢE ALE EDUCAŢIEI, SOCIOLOGIE ȘI ASISTENȚĂ SOCIALĂ'),
    ('FACULTATEA DE RELAŢII INTERNAŢIONALE, ŞTIINŢE POLITICE ŞI ADMINISTRATIVE'),
    ('FACULTATEA DE ŞTIINŢE ECONOMICE');

-- Insert departments
INSERT INTO academic.departments (faculty_id, department_name) VALUES
    (1, 'Departament Biologie şi Ecologie'),
    (1, 'Departament Geoștiințe și Silvicultură'),
    (2, 'Departament Drept Privat'),
    (2, 'Departament Drept Public'),
    (2, 'Departament Drept Penal'),
    (2, 'Departament Drept Procedural'),
    (2, 'Departament Drept Internaţional şi European'),
    (3, 'Departament Chimie'),
    (3, 'Departament Chimie Industrială şi Ecologică'),
    (4, 'Departament Fizică Teoretică ”Iu.Perlin”'),
    (4, 'Departament Fizică Aplicată şi Informatica'),
    (5, 'Departament Istoria Românilor, Universală şi Arheologie'),
    (5, 'Departament Filosofie şi Antropologie'),
    (6, 'Departament Teoria și Practica Jurnalismului'),
    (6, 'Departament Comunicare și Teoria Informării'),
    (7, 'Departament Traducere, Interpretare și Lingvistică Aplicată'),
    (7, 'Departament Lingvistică Română și Știință Literară'),
    (7, 'Departament Filologie Romano-Germanică'),
    (7, 'Departament Literatură Universală și Comparată și Filologie Rusă'),
    (8, 'Departament Matematică'),
    (8, 'Departament Informatică'),
    (9, 'Departament Psihologie'),
    (9, 'Departament Ştiinţe ale Educaţiei'),
    (9, 'Departament Sociologie și Asistență Socială'),
    (10, 'Departament Relaţii Internaţionale'),
    (10, 'Departament Ştiinţe Politice și Administrative'),
    (11, 'Departament Administrarea Afacerilor'),
    (11, 'Departament Finanțe și Bănci'),
    (11, 'Departament Contabilitate'),
    (11, 'Departament Informatică Economică');

-- Insert study programs
INSERT INTO academic.study_programs (department_id, program_name, degree_level, duration_years, credits_required, language) VALUES
(1, 'Biologie (Științe ale Educației)', 'Licență', 3, 180, 'Română'),
(1, 'Biologie (Științe Biologice)', 'Licență', 3, 180, 'Română'),
(1, 'Biologie moleculară', 'Licență', 3, 180, 'Română'),
(1, 'Ecologie și protecția mediului', 'Licență', 3, 180, 'Română'),
(2, 'Silvicultură și grădini publice', 'Licență', 4, 240, 'Română'),
(2, 'Geografie', 'Licență', 3, 180, 'Română'),
(2, 'Arhitectură peisajeră', 'Licență', 4, 240, 'Română'),
(1, 'Științe biologice aplicate', 'Master', 2, 120, 'Română'),
(2, 'Managementul mediului', 'Master', 2, 120, 'Română'),
(2, 'Design de landşaft şi spaţii verzi', 'Master', 2, 120, 'Română'),
(1, 'Biologia moleculară', 'Master', 2, 120, 'Română'),
(4, 'Drept', 'Licență', 4, 240, 'Română'),
(4, 'Drept', 'Licență', 4, 240, 'Rusă'),
(4, 'Drept', 'Licență', 4, 240, 'Engleză'),
(4, 'Drept', 'Licență', 4, 240, 'Franceză'),
(5, 'Drept penal', 'Master', 1.5, 90, 'Română'),
(3, 'Drept civil', 'Master', 1.5, 90, 'Română'),
(6, 'Proceduri judiciare civile', 'Master', 1.5, 90, 'Română'),
(7, 'Drept internațional', 'Master', 1.5, 90, 'Română'),
(5, 'Proces penal și criminalistică', 'Master', 1.5, 90, 'Română'),
(4, 'Drepturile omului', 'Master', 1.5, 90, 'Română'),
(3, 'Dreptul relațiilor de muncă și comerciale în afaceri', 'Master', 1.5, 90, 'Română'),
(4, 'Drept public și guvernare electronică', 'Master', 1.5, 90, 'Română'),
(3, 'Drept fiscal și vamal', 'Master', 1.5, 90, 'Română'),
(3, 'Drept fiscal și activitate vamală', 'Master', 2, 120, 'Română'),
(4, 'Drept public (funcționari publici)', 'Master', 1.5, 90, 'Română'),
(4, 'Anticorupție (funcționari publici)', 'Master', 1.5, 90, 'Română'),
(5, 'Științe penale aplicative', 'Master', 1.5, 90, 'Română'),
(4, 'Drept public (FR, funcționari publici)', 'Master', 1.5, 90, 'Română'),
(4, 'Anticorupție (FR, funcționari publici)', 'Master', 1.5, 90, 'Română'),
(9, 'Tehnologie chimică industrială', 'Licență', 4, 240, 'Română'),
(9, 'Tehnologia produselor cosmetice și medicinale', 'Licență', 4, 240, 'Română'),
(8, 'Chimie (Științe ale Educației)', 'Licență', 3, 180, 'Română'),
(8, 'Chimie (Științe Chimice)', 'Licență', 3, 180, 'Română'),
(8, 'Chimie biofarmaceutică', 'Licență', 3, 180, 'Română'),
(8, 'Materiale avansate în chimie și biofarmaceutică', 'Master', 2, 120, 'Română'),
(9, 'Tehnologii moderne în industria cosmetică, farmaceutică și în protecția mediului', 'Master', 1.5, 90, 'Română'),
(10, 'Fizică (Științe ale Educației)', 'Licență', 3, 180, 'Română'),
(10, 'Fizică (Științe fizice)', 'Licență', 3, 180, 'Română'),
(11, 'Tehnologia informației', 'Licență', 4, 240, 'Română'),
(11, 'Metrologie și instrumentație virtuală', 'Licență', 4, 240, 'Română'),
(10, 'Fizică', 'Master', 2, 120, 'Română'),
(11, 'Tehnologii informaționale în modelare', 'Master', 2, 120, 'Română'),
(11, 'Procedee și metode de măsurare în ingineria mediului', 'Master', 2, 120, 'Română'),
(12, 'Istorie și limba engleză', 'Licență', 4, 240, 'Română'),
(12, 'Istorie (Științe ale Educației)', 'Licență', 3, 180, 'Română'),
(12, 'Istorie (Științe Umaniste)', 'Licență', 3, 180, 'Română'),
(13, 'Antropologie', 'Licență', 3, 180, 'Română'),
(13, 'Filozofie', 'Licență', 3, 180, 'Română'),
(12, 'Stat și societate din perspectivă istorică: forme de guvernare, securitate națională și relații internaționale', 'Master', 2, 120, 'Română'),
(12, 'Managementul Patrimoniului Cultural', 'Master', 2, 120, 'Română'),
(12, 'Istoria și cultura religiilor', 'Master', 2, 120, 'Română'),
(13, 'Filosofie, antropologie și management cultural', 'Master', 2, 120, 'Română'),
(13, 'Filosofii contemporane', 'Master', 2, 120, 'Română'),
(14, 'Comunicare și relații publice', 'Licență', 3, 180, 'Română'),
(14, 'Jurnalism și procese mediatice', 'Licență', 3, 180, 'Română'),
(14, 'Producție multimedia', 'Licență', 3, 180, 'Română'),
(15, 'Biblioteconomie și știința informării', 'Licență', 3, 180, 'Română'),
(14, 'Producție video și media promoting', 'Master', 2, 120, 'Română'),
(15, 'Relații publice și publicitate', 'Master', 2, 120, 'Română'),
(17, 'Limba şi literatura română', 'Licență', 3, 180, 'Română'),
(17, 'Limba şi literatura română şi engleză', 'Licență', 4, 240, 'Română'),
(19, 'Limba şi literatura rusă şi engleză', 'Licență', 4, 240, 'Română'),
(17, 'Limba şi literatura română şi franceză', 'Licență', 4, 240, 'Română'),
(16, 'Traducere și interpretare. Limba engleză şi franceză', 'Licență', 4, 240, 'Română'),
(16, 'Traducere și interpretare. Limba engleză şi germană', 'Licență', 4, 240, 'Română'),
(16, 'Traducere și interpretare. Limba franceză şi engleză', 'Licență', 4, 240, 'Română'),
(16, 'Traducere și interpretare. Limba engleză și italiană', 'Licență', 4, 240, 'Română'),
(18, 'Limba și literatura spaniolă şi engleză', 'Licență', 4, 240, 'Română'),
(18, 'Limba și literatura franceză şi engleză', 'Licență', 4, 240, 'Română'),
(18, 'Limba și literatura engleză și franceză', 'Licență', 4, 240, 'Română'),
(18, 'Limba și literatura germană şi engleză', 'Licență', 4, 240, 'Română'),
(16, 'Comunicare multilingvă, management intercultural şi limbaje de afaceri', 'Master', 2, 120, 'Română'),
(19, 'Limba și literatura rusă', 'Master', 2, 120, 'Română'),
(16, 'Traducere și interpretare de conferințe', 'Master', 2, 120, 'Română'),
(17, 'Studii de filologie română și strategii educaționale', 'Master', 2, 120, 'Română'),
(17, 'Limbă, literatură și civilizație românească', 'Master', 2, 120, 'Română'),
(20, 'Matematică', 'Licență', 3, 180, 'Română'),
(20, 'Matematică (Științe ale Educației)', 'Licență', 3, 180, 'Română'),
(20, 'Matematici aplicate', 'Licență', 3, 180, 'Română'),
(21, 'Informatică (Tehnologii ale informației și comunicațiilor)', 'Licență', 3, 180, 'Română'),
(21, 'Informatică (Științe ale Educației)', 'Licență', 3, 180, 'Română'),
(21, 'Informatică aplicată', 'Licență', 3, 180, 'Română'),
(21, 'Designul jocurilor', 'Licență', 3, 180, 'Română'),
(21, 'Designul jocurilor', 'Licență', 3, 180, 'Engleză'),
(21, 'Designul jocurilor', 'Licență', 3, 180, 'Rusă'),
(23, 'Psihopedagogie', 'Licență', 3, 180, 'Română'),
(23, 'Pedagogie în învățământul primar și limba engleză', 'Licență', 4, 240, 'Română'),
(23, 'Pedagogie în învățământul primar și Psihopedagogie', 'Licență', 4, 240, 'Română'),
(23, 'Educație civică', 'Licență', 3, 180, 'Română'),
(24, 'Sociologie', 'Licență', 3, 180, 'Română'),
(24, 'Asistență socială', 'Licență', 3, 180, 'Română'),
(22, 'Psihologie', 'Licență', 3, 180, 'Română'),
(22, 'Psihologie', 'Licență', 3, 180, 'Rusă'),
(22, 'Psihologie', 'Licență', 3, 180, 'Engleză'),
(22, 'Psihologie clinică', 'Master', 2, 120, 'Română'),
(22, 'Psihologia muncii și organizațională', 'Master', 2, 120, 'Română'),
(22, 'Psihologie judiciară', 'Master', 2, 120, 'Română'),
(23, 'Management educațional', 'Master', 2, 120, 'Română'),
(23, 'Formarea formatorilor', 'Master', 2, 120, 'Română'),
(24, 'Consiliere pentru probleme de familie', 'Master', 2, 120, 'Română'),
(24, 'Managementul serviciilor sociale', 'Master', 2, 120, 'Română'),
(24, 'Sondaje de opinie, marketing și publicitate', 'Master', 2, 120, 'Română'),
(26, 'Politologie', 'Licență', 3, 180, 'Română'),
(26, 'Administrație Publică', 'Licență', 3, 180, 'Română'),
(25, 'Relații Internaționale', 'Licență', 3, 180, 'Română'),
(25, 'Relații Internaționale', 'Licență', 3, 180, 'Engleză'),
(25, 'Relații Internaționale', 'Licență', 3, 180, 'Franceză'),
(25, 'Relații Internaționale', 'Licență', 3, 180, 'Rusă'),
(25, 'Studii diplomatice', 'Master', 2, 120, 'Română'),
(25, 'Studii europene', 'Master', 2, 120, 'Română'),
(26, 'Politici și servicii publice', 'Master', 2, 120, 'Română'),
(26, 'Studii de Securitate Națională', 'Master', 2, 120, 'Română'),
(25, 'Relații Internaționale (master, frecvență redusă)', 'Master', 2, 120, 'Română'),
(25, 'Relații Internaționale (master, frecvență)', 'Master', 2, 120, 'Română'),
(26, 'Administrare Publică (master, frecvență redusă)', 'Master', 2, 120, 'Română'),
(26, 'Administrare Publică (master, frecvență)', 'Master', 2, 120, 'Română'),
(26, 'Management politic și electoral', 'Master', 2, 120, 'Română'),
(27, 'Business și administrare', 'Licență', 3, 180, 'Română'),
(27, 'Business și administrare', 'Licență', 3, 180, 'Engleză'),
(27, 'Business și administrare', 'Licență', 3, 180, 'Franceză'),
(27, 'Business și administrare', 'Licență', 3, 180, 'Rusă'),
(29, 'Contabilitate', 'Licență', 3, 180, 'Română'),
(29, 'Contabilitate', 'Licență', 3, 180, 'Franceză'),
(29, 'Contabilitate', 'Licență', 3, 180, 'Rusă'),
(28, 'Finanțe și bănci', 'Licență', 3, 180, 'Română'),
(28, 'Finanțe și bănci', 'Licență', 3, 180, 'Engleză'),
(28, 'Finanțe și bănci', 'Licență', 3, 180, 'Franceză'),
(28, 'Finanțe și bănci', 'Licență', 3, 180, 'Rusă'),
(27, 'Marketing și logistică', 'Licență', 3, 180, 'Română'),
(27, 'Marketing și logistică', 'Licență', 3, 180, 'Engleză'),
(27, 'Marketing și logistică', 'Licență', 3, 180, 'Franceză'),
(27, 'Marketing și logistică', 'Licență', 3, 180, 'Rusă'),
(27, 'Servicii hoteliere, turism și agrement', 'Licență', 3, 180, 'Română'),
(27, 'Servicii hoteliere, turism și agrement', 'Licență', 3, 180, 'Engleză'),
(27, 'Servicii hoteliere, turism și agrement', 'Licență', 3, 180, 'Franceză'),
(27, 'Servicii hoteliere, turism și agrement', 'Licență', 3, 180, 'Rusă'),
(28, 'Audit şi expertiză financiară', 'Master', 2, 120, 'Română'),
(28, 'Administrare bancară', 'Master', 2, 120, 'Română'),
(29, 'Contabilitatea întreprinderii', 'Master', 2, 120, 'Română'),
(28, 'Finanţe publice şi fiscalitate', 'Master', 2, 120, 'Română'),
(27, 'Administrarea afacerilor', 'Master', 2, 120, 'Română'),
(28, 'Gestiunea finanţelor şi contabilitatea în afaceri', 'Master', 2, 120, 'Română'),
(27, 'Managementul resurselor umane', 'Master', 2, 120, 'Română'),
(27, 'Studii în marketing', 'Master', 2, 120, 'Română'),
(27, 'Management şi marketing hotelier şi turism', 'Master', 2, 120, 'Română'),
(27, 'Management (inclusiv pentru funcționari publici)', 'Master', 2, 120, 'Română'),
(30, 'Baze de date şi tehnici actuariale', 'Master', 2, 120, 'Română'),
(27, 'Management (cu frecvență redusă, inclusiv pentru funcționari publici)', 'Master', 2, 120, 'Română');
